server:
  port: 80
  servlet:
    encoding:
      charset: UTF-8
      force: true
spring:
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
logging:
  level:
    root: info

app:
  dir:
    imgdir: file:///C:\Spring_Hanaro\sb2\imgs
    logdir: file:///C:\Spring_Hanaro\sb2\logs

    # /root/logs/